@section('main_contents')
@extends('admin_views.layout.Layout')
@include('admin_views.header.Header')
@include('admin_views.header.TopHeader')
@include('admin_views.navigation.Navbar')
@include('admin_views.dashbaord.DashbaordContent')
@endsection()
